---
functional:
  - требование 3
  - требование 4
  - требование 7
  - требование 8
non-functional:
  - требование 1
  - требование 2 
  - требование 5
  - требование 6
implicit:
  - требование 9
  - требование "Сайт должен иметь возможность сохранять информацию о содержимом в корзине и информацию о совершенных заказах.
  - требование "Сайт должен иметь возможность выбора количества добавляемого товара.
  - требование "Сайт должен адаптироваться под любое разрешение (изменять размер кнопок).
